name: Laerdal Labs, DC GStreamer Plugin Windows Build
on:
  push:
    branches: [ master ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build-package:
    name: Build Windows Nuget Package
    runs-on: windows-2022
    defaults:
      run:
        working-directory: aws-s3-gst-plugin
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: aws-s3-gst-plugin 

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install meson/ninja
        run: pip install meson ninja

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1.3

      - name: Setup VS Dev Environment
        uses: seanmiddleditch/gha-setup-vsdevenv@v4

      - name: Install GStreamer
        id: setup_gstreamer
        uses: blinemedical/setup-gstreamer@v1.1.0
        with:
          version: '1.22.4'
          arch: 'x86_64'

      - name: Add GStreamer to the environment/path (Windows)
        run: |
          chcp 65001 #set code page to utf-8
          echo ("GSTREAMER_1_0_ROOT_MSVC_X86_64=${{ steps.setup_gstreamer.outputs.gstreamerPath }}") >> $env:GITHUB_ENV
          echo ("${{ steps.setup_gstreamer.outputs.gstreamerPath }}\bin") | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
      
      - name: Clone supercharge docs repository
        uses: actions/checkout@v2
        with:
          repository: blinemedical/aws-sdk-cpp
          path: ./aws-sdk-cpp
      
      - name: Clone and Build bline/aws-sdk-cpp
        run: | 
          'cd ./aws-sdk-cpp'
          cmake  -S . -B build -G "Visual Studio 17 2022" -DBUILD_ONLY="s3;sts" -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX:PATH=C:/aws-cpp-sdk-all aws-sdk-cpp
          cmake --build build -j --config Debug
          cmake --install build --config Debug
        